package com.example.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val appName: String,
    val dashboard: String,
    val logs: String,
    val settings: String,
    val about: String,
    val start: String,
    val stop: String,
    val txTitle: String,
    val rxTitle: String,
    val activeFlows: String,
    val targetAddress: String,
    val connectionTipTitle: String,
    val connectionTipBody: String,
    val copyProxyBtn: String,
    val terminalTitle: String,
    val clearLogs: String,
    val copyLogs: String,
    val terminalIdleTitle: String,
    val terminalIdleSubtitle: String,
    val settingsTitle: String,
    val settingsSubtitle: String,
    val listenPortLabel: String,
    val connectHostLabel: String,
    val connectPortLabel: String,
    val sniSelectionLabel: String,
    val customSniLabel: String,
    val bypassStrategyLabel: String,
    val strategyTcpTitle: String,
    val strategyTcpDesc: String,
    val strategyDirectTitle: String,
    val strategyDirectDesc: String,
    val themeLabel: String,
    val languageLabel: String,
    val logsCopiedMsg: String,
    val logsClearedMsg: String,
    val githubLinkTitle: String,
    val githubSubTitle: String,
    val openGithubBtn: String,
    val simulatorInfo: String,
    val appPreferencesTitle: String,
    val proxyConfigTitle: String,
    val saveChanges: String,
    val systemDefault: String,
    val authorGithubTitle: String,
    val authorGithubSubTitle: String,
    val poweredByTitle: String,
    val poweredBySubTitle: String,
    val notificationTitle: String,
    val notificationText: String,
    val designBy: String,
    val poweredByDashboard: String,
    val errorPortRange: String,
    val errorEmptySni: String
)

val EnglishStrings = AppStrings(
    appName = "SNI Spoofing",
    dashboard = "Dashboard",
    logs = "Logs",
    settings = "Settings",
    about = "About",
    start = "START",
    stop = "STOP SPOOFING",
    txTitle = "Transmitted (TX)",
    rxTitle = "Received (RX)",
    activeFlows = "ACTIVE FLOWS",
    targetAddress = "TARGET ADDRESS",
    connectionTipTitle = "💡 How to use this Proxy in apps like Hiddify or V2rayNG:",
    connectionTipBody = "1. Start this app (Proxy running on loopback).\n2. DO NOT use VPN mode for this app (exclude it if possible, or ensure it only proxies other apps).\n3. In your client (Hiddify/v2rayNG), apply configs exactly as generated with SNI, but point their proxy routing address (or manual host connection) to 127.0.0.1 and this proxy's port.\nThe proxy will automatically spoof SNI strings during TLS handshake outbound.",
    copyProxyBtn = "Copy Proxy",
    terminalTitle = "REAL-TIME DPI BYPASS LOGS",
    clearLogs = "CLEAR",
    copyLogs = "COPY LOGS",
    terminalIdleTitle = ">_ Terminal Idle",
    terminalIdleSubtitle = "Start the tunnel to intercept & fragment local flows",
    settingsTitle = "TUNNEL PROXY CONFIGURATION",
    settingsSubtitle = "Configure routing parameters. Re-start proxy to apply.",
    listenPortLabel = "Local Proxy Listen Port",
    connectHostLabel = "Target Remote Host / IP address",
    connectPortLabel = "Target Port (HTTPS/TLS is usually 443)",
    sniSelectionLabel = "Decoy SNI Hostname Presets",
    customSniLabel = "Custom Extra SNI",
    bypassStrategyLabel = "Bypass Strategy Selection:",
    strategyTcpTitle = "Split Handshake Flight (TCP Segmentation)",
    strategyTcpDesc = "No Root Required. Segments TLS ClientHello headers to confuse passive DPI parsers.",
    strategyDirectTitle = "Direct Port Forwarding (Pass-through)",
    strategyDirectDesc = "Disable bypass filters. Forward standard TCP payload stream completely unmodified.",
    themeLabel = "App Theme (Dark / Light)",
    languageLabel = "App Language (Eng / Fa)",
    logsCopiedMsg = "Logs copied to clipboard!",
    logsClearedMsg = "Logs cleared.",
    githubLinkTitle = "Open Source Project",
    githubSubTitle = "SNI-Spoofing by patterniha on GitHub",
    openGithubBtn = "Open Link",
    simulatorInfo = "How it works?",
    appPreferencesTitle = "App Preferences",
    proxyConfigTitle = "Proxy Configuration",
    saveChanges = "SAVE",
    systemDefault = "System Default",
    authorGithubTitle = "Author",
    authorGithubSubTitle = "SNI-Spoofing-Android by Mr-MinGo",
    poweredByTitle = "Powered By",
    poweredBySubTitle = "Core logic based on SNI-Spoofing by patterniha",
    notificationTitle = "SNI Spoofing is Active",
    notificationText = "Proxy is running in the background on 127.0.0.1",
    designBy = "Designed by Mr-MinGo",
    poweredByDashboard = "Powered by patterniha",
    errorPortRange = "Port must be between 1 and 65535",
    errorEmptySni = "Custom SNI cannot be empty"
)

val PersianStrings = AppStrings(
    appName = "SNI Spoofing",
    dashboard = "داشبورد",
    logs = "لاگ‌ها",
    settings = "تنظیمات",
    about = "درباره",
    start = "شروع",
    stop = "STOP SPOOFING",
    txTitle = "ارسال شده (TX)",
    rxTitle = "دریافت شده (RX)",
    activeFlows = "اتصالات فعال",
    targetAddress = "آدرس نقصد",
    connectionTipTitle = "💡 نحوه استفاده در برنامه‌هایی نظیر Hiddify یا V2rayNG:",
    connectionTipBody = "۱. این پروکسی را استارت بزنید (روی لوکال‌هاست اجرا می‌شود).\n۲. از تانل شدن کل گوشی (VPN mode) برای خود این برنامه جلوگیری کنید (این برنامه نباید از vpn رد شود).\n۳. در برنامه‌های کاربری (سینگ‌باکس یا Xray)، کانفیگ‌های حاوی دامنه SNI را وارد کنید، اما آی‌پی سرور (Host) یا مسیر پراکسی را روی 127.0.0.1 و پورت لوکال تنظیم کنید.\nبرنامه به‌طور خودکار بسته‌های TLS را برای دور زدن فیلترینگ (DPI) بخش‌بندی می‌کند.",
    copyProxyBtn = "کپی پروکسی",
    terminalTitle = "گزارشات زنده دور زدن DPI",
    clearLogs = "پاکسازی",
    copyLogs = "کپی لاگ",
    terminalIdleTitle = ">_ ترمینال غیرفعال",
    terminalIdleSubtitle = "تونل را استارت کنید تا لاگ‌ها نمایش داده شوند",
    settingsTitle = "پیکربندی اطلاعات پروکسی",
    settingsSubtitle = "تنظیمات مسیردهی. برای اعمال تغییرات پروکسی را ری‌استارت کنید.",
    listenPortLabel = "پورت محلی پروکسی",
    connectHostLabel = "آی‌پی تمیز یا هاست سرور مقصد",
    connectPortLabel = "پورت مقصد (معمولا 443)",
    sniSelectionLabel = "لیست آماده SNI های فیک",
    customSniLabel = "SNI دلخواه (Custom)",
    bypassStrategyLabel = "انتخاب روش عبور:",
    strategyTcpTitle = "تقسیم بسته (TCP Segmentation)",
    strategyTcpDesc = "بدون نیاز به روت. هدر TLS ClientHello را بخش‌بندی می‌کند تا DPI متوجه SNI نشود.",
    strategyDirectTitle = "ارسال مستقیم (Pass-through)",
    strategyDirectDesc = "غیرفعال کردن فیلتر دور زدن. ترافیک عادی عبور داده می‌شود.",
    themeLabel = "پوسته برنامه (تاریک / روشن)",
    languageLabel = "زبان برنامه (انگلیسی / فارسی)",
    logsCopiedMsg = "لاگ‌ها در کلیپ‌بورد ذخیره شدند!",
    logsClearedMsg = "لاگ‌ها با موفقیت پاک شدند.",
    githubLinkTitle = "پروژه متن‌باز گیتهاب",
    githubSubTitle = "SNI-Spoofing کاری از patterniha",
    openGithubBtn = "باز کردن لینک",
    simulatorInfo = "چطوری کار می‌کنه؟ (How it works)",
    appPreferencesTitle = "تنظیمات برنامه",
    proxyConfigTitle = "پیکربندی پروکسی",
    saveChanges = "ذخیره کردن",
    systemDefault = "پیش‌فرض سیستم",
    authorGithubTitle = "توسعه‌دهنده",
    authorGithubSubTitle = "پروژه اندروید توسط Mr-MinGo",
    poweredByTitle = "قدرت گرفته از",
    poweredBySubTitle = "منطق اصلی بر اساس کد patterniha",
    notificationTitle = "دور زدن کلاینت فعال است",
    notificationText = "پروکسی در پس‌زمینه روی 127.0.0.1 در حال اجراست",
    designBy = "طراحی توسط Mr-MinGo",
    poweredByDashboard = "قدرت گرفته از patterniha",
    errorPortRange = "پورت باید بین ۱ تا ۶۵۵۳۵ باشد",
    errorEmptySni = "SNI نمی‌تواند خالی باشد"
)

val LocalStrings = staticCompositionLocalOf { EnglishStrings }
